### ISSUE TITLE
Replace http CDN links to js libs with https

### ISSUE THREAD

**Issue by alkersan** [jrudolph/sbt-dependency-graph#102]
Motivation: ability to publish dependency-graph html results on https enabled sites.
Currently, if resulting grapht.html is hosted on https site - most browsers will reject to download [linked javascripts](https://github.com/jrudolph/sbt-dependency-graph/blob/master/src/main/resources/graph.html#L34) due to [blocked mixed content policy](https://developer.mozilla.org/en-US/docs/Security/Mixed_content/How_to_fix_website_with_mixed_content).

Please, update CDN links to https ones:
 - https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js
 - https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js
 - https://raw.githubusercontent.com/cpettitt/graphlib-dot/v0.6.1/dist/graphlib-dot.min.js
 - https://raw.githubusercontent.com/cpettitt/dagre-d3/v0.4.16/dist/dagre-d3.min.js

**Comment by jrudolph** [comment]
Thanks, @alkersan. Good point. Could you open a PR?

**Comment by alkersan** [comment]
Done
