### ISSUE TITLE
Doesn't appear to be have properly as a global plugin

### ISSUE THREAD

**Issue by nrinaudo** [jrudolph/sbt-dependency-graph#106]
On my configuration (sbt 0.13.11), `sbt-dependency-graph` has a very weird behaviour as a global plugin: most of the time, it will silently fail to load - that is, no error is reported, but the expected commands are not available.

If I manually delete `~/.sbt/0.13/target/` and `~/.sbt/0.13/plugings/target/`, however, it will load successfully on the next attempt, and the next attempt only.

I'm assuming this is something on my end or I wouldn't be the first to report this issue, but do you know of anything that could explain this behaviour?

**Comment by jrudolph** [comment]
Interesting. We had quite some reports of similar issues where the global configuration didn't work reliably under some circumstances which couldn't be reproduced exactly so far.

Would be nice to have a reproducer for this to investigate further. You could try to use https://github.com/paulp/sbt-extras to run sbt and then vary some options to see where in your configuration is the problem. Most importantly try another sbt configuration directory with `-sbt-dir` to see if that's the problem.

**Comment by nrinaudo** [comment]
The "bad" news is that the problem seems to have sorted itself out, and I don't really know why. If it pops up again I'll try and play with sbt-extras to see if I can get you more reliable debug informations.

**Comment by jrudolph** [comment]
Ok, no worries. Let's close it for now :)
