### ISSUE TITLE
Allow running whatDependsOn without version number

### ISSUE THREAD

**Issue by benmccann** [jrudolph/sbt-dependency-graph#110]
I'd really like to be able to run `whatDependsOn` without needing the version number.

E.g. right now I'm trying to track down a problem that I know is caused by having both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the classpath, but I don't know what versions are being transitively pulled in. I tried running `dependencyTree`, but it took half an hour and died with an out of heap space error. Even if I did know the version numbers of the jars it would be more convenient to have the version number be optional

**Comment by smartnut007** [comment]
👍

**Comment by t3hnar** [comment]
👍

**Comment by pshirshov** [comment]
It would be great to have this, I would even pay for such a feature :)

**Comment by t3hnar** [comment]
@benmccann this could be interesting https://github.com/evolution-gaming/no-log4j-test

**Comment by pshirshov** [comment]
Guys, just in case, look at this stuff: https://github.com/pshirshov/izumi-r2/blob/develop/sbt/sbt-izumi-deps/src/main/scala/com/github/pshirshov/izumi/sbt/deps/IzumiBuildInfoPlugin.scala#L121

This way you may introspect the whole project from a single task execution, so you wouldn't need to execute same task in all the submodules.

**Comment by jrudolph** [comment]
This feature will be in 0.9.1.
