### ISSUE TITLE
v0.8.3 Release?

### ISSUE THREAD

**Issue by aadrian** [jrudolph/sbt-dependency-graph#118]
Could we please have a v0.8.3 Release (that would include the PRs too?)

Thank you.

**Comment by jrudolph** [comment]
Which changes are you looking for? Not sure when I will have time to got through the PRs, but some seem like they should be merged.

**Comment by aadrian** [comment]
> Which changes are you looking for?

As many as possible? :)

**Comment by limansky** [comment]
@jrudolph at least it supports sbt-1.0.x

**Comment by jrudolph** [comment]
I'm closing this for now. 0.9.0 for sbt 1.0 was released. I guess the pending PRs will have lots of conflicts now because of the migration. Let's see what we want and are able to salvage for the next version.
