### ISSUE TITLE
doesn't support strict conflict manager

### ISSUE THREAD

**Issue by fommil** [jrudolph/sbt-dependency-graph#120]
`conflictManager := ConflictManager.strict` usually breaks this plugin

e.g. try using with this (arbitrary cut of) ensime

https://github.com/ensime/ensime-server/commit/4e580733ff5bb722e75d91e51af4ab004da804ce

**Comment by jrudolph** [comment]
Hi @fommil, thanks for the report. What exactly does break?

**Comment by fommil** [comment]
it outputs a bunch of stuff like this

```
[error] (jerky/*:ivyReport::update) org.apache.ivy.plugins.conflict.StrictConflictException: org.scala-lang.modules#scala-xml_2.12;1.0.5 (needed by [org.scalatest#scalatest_2.12;3.0.1]) conflicts with org.scala-lang.modules#scala-xml_2.12;1.0.6 (needed by [org.scala-lang#scala-compiler;2.12.1, org.scala-lang#scala-compiler;2.12.1, org.scala-lang#scala-compiler;2.12.1, org.scala-lang#scala-compiler;2.12.1, org.scala-lang#scala-compiler;2.12.1, org.scala-lang#scala-compiler;2.12.1])
```

the workaround is easy, just `set every conflictManager := ConflictManager.default` before running `dependencyTree`.
