### ISSUE TITLE
No Tree or List on some projects.

### ISSUE THREAD

**Issue by aadrian** [jrudolph/sbt-dependency-graph#124]
Hi,

The actual version (0.8.2) installed globally, doesn't seem to produce any list or tree on this project:
https://github.com/nus/gitbucket-plantuml-plugin
even if that project does have some dependencies. The only output is the project  name.

Thank you.

**Comment by jrudolph** [comment]
It seems the project has only `provided` dependencies. Try using `provided:dependencyBrowseTree` or similar to view the depedency tree for that configuration.

**Comment by bzz** [comment]
👍 `./sbt provided:dependencyBrowseGraph` did the trick
