### ISSUE TITLE
Don't depend on sbt's JLine

### ISSUE THREAD

**Issue by dwijnand** [jrudolph/sbt-dependency-graph#132]
@eed3si9n and I noticed that you're using `JLine.usingTerminal(_.getWidth)` in https://github.com/jrudolph/sbt-dependency-graph/blob/master/src/main/scala/sbt/SbtAccess.scala.

We're starting to think about moving from JLine2 to JLine3, but what you're doing there makes you dependant on JLine's binary API (jline.Terminal).

What we want to do is add an sbt API to provide you the same functionality, so you don't depend directly on: https://github.com/sbt/sbt/issues/3352

So please consider this ticket before releasing a build for sbt 1.

**Comment by jrudolph** [comment]
The current version still depends on internals but I agree that moving to the new `terminalWidth` API is the way to go.

**Comment by dwijnand** [comment]
Done in #137. Thanks @jrudolph!
