### ISSUE TITLE
Add sbt-plugin topic for Scaladex

### ISSUE THREAD

**Issue by sbrunk** [jrudolph/sbt-dependency-graph#133]
Scaladex lets you filter sbt plugins:
https://index.scala-lang.org/search?topics=sbt-plugin

It reads metadata from GitHub so tagging the project here with the "sbt-plugin" topic should be enough for it to show up as sbt plugin (after the next Scaladex index update).

**Comment by jrudolph** [comment]
Good idea, thanks. Done :)
