### ISSUE TITLE
sbt 1.0 release

### ISSUE THREAD

**Issue by pjfanning** [jrudolph/sbt-dependency-graph#134]
Is there a plan to release an sbt 1.0 compatible plugin? https://github.com/jrudolph/sbt-dependency-graph/issues/132 is related.
I had a quick look regarding the sbt-dependency-graph build and found that sbt-pgp 1.1.0-M1 supports sbt 1.0. I raised https://github.com/sbt/sbt-scalariform/issues/64. There seems to be more required for the sbt scripted-plugin than just uptaking org.scala-sbt#scripted-plugin_2.12;1.0.0.
I've tried the sbt-coursier plugin and it does work but it doesn't have the same features as this plugin.

**Comment by jrudolph** [comment]
Yes, definitely, there will be a release for sbt 1.0. Just didn't get to it
due to summer outside  :)

**Comment by hseeberger** [comment]
Summer outside? Not in Germany right now ;-)

**Comment by jrudolph** [comment]
I had a look at sbt 1.0 support at the weekend. It's far from trivial:

 * sbt-dependency-graph uses data structures from sbt to figure out the dependency graph that probably can be considered internal to sbt and seem to have changed in sbt 1.0. I haven't looked into that in detail so I cannot even estimate what amount of work it would take to update / rewrite the core part of sbt-dependency-graph. In the best case things have just been moved around.
 * sbt-dependency-graph still uses old (non-macro-based) Task definition syntax, this doesn't work any more in sbt 1.0, so the syntax needs to be adapted everywhere (simple to change but annoying)
 * (minor) ascii-graph currently has no 2.12 version. For now, I'd just disable the `dependencyGraph` task for sbt 1.0, it was only useful for pretty small graphs any way.
 * I need to decide whether to support cross-building for sbt 0.13.x and 1.x from one code-base. It might be a hassle in which case the current working 0.13 version could be maintained in its own branch. On the other hand, it would be definitely less confusing for users if there'd be only a single code base working for 0.13 and 1.0 at least for the time being. It might even be more efficient to make careful changes to still support 0.13 as well.

I'm treating this with some priority but depending on the amount of work it might still take a while. If someone wants to help just taking the existing code and fixing the deprecations against sbt 0.13 would help a lot.

**Comment by jrudolph** [comment]
> If someone wants to help just taking the existing code and fixing the deprecations against sbt 0.13 would help a lot.

I managed to do these mostly yesterday evening. Someone also pointed to an old branch at https://github.com/jrudolph/sbt-dependency-graph/tree/w/sbt-1.0.0-M4-support I had forgotten about that could help with the first bullet point.

**Comment by kamilkloch** [comment]
sbt 1.0.1 is there :)

**Comment by jrudolph** [comment]
> sbt 1.0.1 is there :)

Unfortunately, it hasn't fixed bugs like https://github.com/sbt/sbt/issues/3299.

Anyway I have published a 0.8.3-SNAPSHOT version to sonatype for the brave ones.

**Comment by stephennancekivell** [comment]
Thanks for publishing the snapshot. I've given it a go on a fairly large project (~ 150 deps) without any issue.

**Comment by dwijnand** [comment]
Is sbt/sbt#3299 a show-stopping bug?

**Comment by dwijnand** [comment]
With regards to cross-building please note that https://github.com/dwijnand/sbt-compat is available, and I'm happy to accept changes for any shim required by sbt-dependency-graph.

**Comment by akauppi** [comment]
@dwijnand [sbt/sbt#3299](https://github.com/sbt/sbt/issues/3299) was closed 7 days ago.

**Comment by benblack86** [comment]
0.8.3-SNAPSHOT is working well for me

**Comment by sarahgerweck** [comment]
Seems like people are having good luck with the snapshot, and the prereq issues are fixed: Is it time to release 0.8.3 (or 0.9)?

**Comment by MasseGuillaume** [comment]
As part of [SCP-013](https://github.com/scalacenter/advisoryboard/blob/master/proposals/013-sbt-migration.md#scp-013-aid-the-ecosystem-in-upgrading-to-sbt-10x) the Scala Center has the task to help the community migrate their plugins.

Since this plugin is on the top of the [sbt 1.0 migration list](https://github.com/sbt/sbt/wiki/sbt-1.x-plugin-migration) we are offering our help.

Here is my plan:

* [ ] Upgrade from 0.13.8 to 0.13.16 (<<= vs .value)
* [ ] Release ascii-graph for 2.12
* [ ] Enable cross building for 0.13 and 1.0

**Comment by MasseGuillaume** [comment]
Just completed the first phase: https://github.com/jrudolph/sbt-dependency-graph/pull/139

**Comment by jrudolph** [comment]
@MasseGuillaume sorry for not answering any sooner here. Have you seen #137 and #138? This contains the current state of the migration. I think the simple things have mostly been solved and I published a SNAPSHOT of sbt 1.0 support a while ago from that branch. However, I'd like to be able to keep cross-building to sbt 0.13. So, basically what's missing is taking #137/#138 and make sure that they can be cross-built against 0.13.

**Comment by MasseGuillaume** [comment]
Yep I saw both branches. I took a bit of your work in #137 I can add you as an author in the commit message if you want.

**Comment by MasseGuillaume** [comment]
@jrudolph 

sbt-dependency-graph is now cross compiled between sbt 1.0 and 0.13

You need to merge #139 then #140. Then you can publish with `sbt "^ publish"`. Let me know If I missed anything.

**Comment by jrudolph** [comment]
Wow that was fast. Thanks a lot. I'll take it for a spin later on :+1:

Am 17.10.2017 8:57 vorm. schrieb "Guillaume Massé" <notifications@github.com

**Comment by sarahgerweck** [comment]
Is there anything the community can do to help get this released?

**Comment by jrudolph** [comment]
I just merged all the pending PRs for the 1.0 upgrade and released 0.9.0 for both sbt 0.13 and 1.0.

Thanks a lot again, @MasseGuillaume and Scala Center for helping out to get this finally resolved.

**Comment by slandelle** [comment]
Thanks a bunch!!!
