### ISSUE TITLE
Add support for writing Flat dependency list to file

### ISSUE THREAD

**Issue by anuccio1** [jrudolph/sbt-dependency-graph#149]
I would like to run something like `dependencyList`, however have it write the results to a file.

**Comment by alexfichel** [comment]
You can try saving out to a file:

`sbt dependencyList > file.txt`

To remove all the console formating chars from file add option:

`sbt dependencyList -Dsbt.log.format=false`

**Comment by jrudolph** [comment]
Will be fixed by #165.
