### ISSUE TITLE
render a dependency graph in the browser

### ISSUE THREAD

**Issue by MasseGuillaume** [jrudolph/sbt-dependency-graph#29]
as a impatient developer I want to see the decency graph as quick as possible ( without installing 3rd parties ). I would love to see a graph in my web browser. In fact this is doable with canviz and a dotfile ( http://www.ryandesign.com/canviz )

https://code.google.com/p/canviz/

**Comment by jrudolph** [comment]
I released a new version 0.8.0-beta1 (to sonatype, wait a few hours to let it appear on maven central) which has implemented a first version of this feature. Try `dependencyBrowseGraph`.
