### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by ShengC** [jrudolph/sbt-dependency-graph#39]
I already see lots of people reported the similar issue before. Although this has been claimed to be fixed in the version prior to 0.7.4 (which is the one I am using), it still persists for my case

> project foo
> dependency-graph
[trace] Stack trace suppressed: run last foo/compile:module-graph for the full output.
[error] (foo/compile:module-graph) java.io.FileNotFoundException: /home/shengc/foo/target/resolution-cache/reports/net.foo-foo/compile-resolved.xml (No such file or directory)
[error] Total time: 10 s, completed Sep 12, 2013 9:53:18 AM

So
1. I have a aggregated project, and I use "project foo" to go into a sub-project
2. I am using ivy/ivysettings for dependency management

Would these 2 by any means mess the search path of this plugin?

**Comment by nitay** [comment]
I'm getting this in a multi module project. I don't have any custom ivysettings.
I don't fully understand @velvia's solution - how does limiting parallelism of tests effect dependency graph execution?

**Comment by jkleckner** [comment]
FYI, I started hitting this when I added crossScalaVersions.
This is with a multi-module project.
These steps had these effects:
* Removing crossScalaVersions eliminated the race condition.
* Restoring crossScalaVersions restored the race condition.
* Running a second time succeeded now that the compile.xml file was present.
This suggests that there is more than one task spun up for the scala versions.
Touching the build.sbt file cleans out the compile.xml file triggering the race.
This is with plugin 0.7.5 and sbt 0.13.7
Hope this helps.

**Comment by jkleckner** [comment]
Could it be that the ```main/*:ivyReport::update``` and ```main/*:ivyReportFunction``` tasks do not have dependencies set correctly?
```
> inspect tree  main/compile:dependencyTree
[info] main/compile:dependencyTree = Task[Unit]
[info]   +-main/compile:dependencyTree::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   |
[info]   +-main/compile:dependencyTreeString = Task[java.lang.String]
[info]     +-main/compile:moduleGraph = Task[net.virtualvoid.sbt.graph.IvyGraphMLDependencies$ModuleGraph]
[info]       +-*/*:filterScalaLibrary = true
[info]       +-main/compile:ivyReport = Task[java.io.File]
[info]       | +-main/*:ivyReport::update = Task[sbt.UpdateReport]
[info]       | +-main/*:ivyReportFunction = Task[scala.Function1[java.lang.String, java.io.File]]
[info]       |
[info]       +-main/*:scalaVersion = 2.11.7
[info]
```

**Comment by laser** [comment]
@velvia - Thanks for posting an example of how you worked around this issue by limiting the number of parallelizable tasks (to 0). Helped me out tremendously.

**Comment by jkleckner** [comment]
@laser Could you post what you used?  Did you limit the scope to the dependencyTree task?

**Comment by jrudolph** [comment]
I released a new version 0.8.0-beta1 (to sonatype, wait a few hours to let it appear on maven central) which should have fixed this issue.

Maybe someone would like to test?

**Comment by fakraemer** [comment]
I was just hitting the same issue using what-depends-on with 0.7.5, can confirm that it works now on 0.8.0-beta1. I had to remove net.virtualvoid.sbt.graph.Plugin.graphSettings from global.sbt (I guess it's an  AutoPlugin now?). Anyway, thanks for fixing this!

**Comment by jkleckner** [comment]
@jrudolph The project that previously failed ran to completion with 0.8.0-beta1.  Thank you!
