### ISSUE TITLE
Figure out resolution-cache directory more intelligently

### ISSUE THREAD

**Issue by fommil** [jrudolph/sbt-dependency-graph#43]
[this stackoverflow hack](http://stackoverflow.com/questions/17190755) shows how to set an ivy resolver cache that is outside the `target` directory and therefore immune to insane slowdown on a `clean`. When I do this, I set it on a per-module basis.

However, sbt dependency graph seems to be referencing the old cache directory. Is this hardcoded or is there something else I have to do to get it to use the new cache?

**Comment by jrudolph** [comment]
This is now mostly fixed by implementing an sbt backend to generate the graph. See #39
