### ISSUE TITLE
Dot output should show evicted by version

### ISSUE THREAD

**Issue by analytically** [jrudolph/sbt-dependency-graph#48]
At the moment the dot output shows you the original version. This should show which version is actually used (the evicted by version).

**Comment by jrudolph** [comment]
This has been fixed in https://github.com/jrudolph/sbt-dependency-graph/commit/ac0ab5189a3ca9d9e7b893bad275dd394df89b53 by creating a "virtual" dependency chain of

module -> evicted library -> evicted by library

in the dot dependency graph.
