### ISSUE TITLE
Add support for auto plugins in sbt 0.13.5

### ISSUE THREAD

**Issue by jasonchaffee** [jrudolph/sbt-dependency-graph#51]
Add support for auto plugins in sbt 0.13.5

**Comment by pauldraper** [comment]
The real benefit would come by enabling this by default (which is possible with auto plugins).

This would work very well for this plugin, as this plugin doesn't change any existing behavior; it just adds a few tasks.

I could query dependencies on an personal, work, open-source, etc. project, without having to ever touch the build definition.

**Comment by metasim** [comment]
I'd also appreciate having this as an autoPlugin. That way one can have in in the sbt global plugins and have the settings automatically merged without changing shared build files.

**Comment by muuki88** [comment]
I could make a pull request, but I'm not familiar with the sbt-crosscompile stuff and how to handle this. How important is the backwards compatibility with sbt `12.x` and pre `13.5`?

**Comment by jrudolph** [comment]
Thanks @muuki88 for the offer. I'm just wrapping up a new version which also has autoplugin support which I hope to have ready soon. So, don't bother with a PR this time.

**Comment by jrudolph** [comment]
Fixed in https://github.com/jrudolph/sbt-dependency-graph/commit/adc55e31a72fed0fa630c70c8f3b731c80516066.
