### ISSUE TITLE
Issue when executing 'what-depends-on' command

### ISSUE THREAD

**Issue by aparamonov** [jrudolph/sbt-dependency-graph#52]
Hi,

I'm trying execute following command:

```
sbt "project my-project" what-depends-on org.scalamacros quasiquotes_2.10.3 2.0.0-M3
```

but I faced with following error message:

```
[error] Not a valid command: what-depends-on
[error] Expected whitespace character
[error] what-depends-on
[error]                ^
```

Symbol '^' points on the symbole after "-on".

Command "sbt "project my-project" dependency-tree" works fine.

**Comment by radumanolescu** [comment]
Using "sbt-dependency-graph" % "0.8.2" with sbt 0.13.13, java  1.8.0_102-b14 on Babun Cygwin on Windows7. Trying to get "what depends on" on a multi-project build, using Ivy for dependency management, getting exception and no output.
`sbt "what-depends-on org.slf4j slf4j-api 1.7.21"`

Getting this exception for each project of my multi-project build:
`java.util.NoSuchElementException: key not found: ModuleId(com.myCo.myProj,myProj-some-name,0.0.+)`

I can provide the stack trace (all 400 lines of it).
The projects all compile, i.e. "sbt compile", "sbt package" all work.
What am I doing wrong / how can I fix this?

**Comment by jrudolph** [comment]
Thanks, @radumanolescu. More stack trace would be helpful. You may also open a new issue for that.
