### ISSUE TITLE
sbt 0.13.8 support

### ISSUE THREAD

**Issue by sslavic** [jrudolph/sbt-dependency-graph#67]
sbt 0.13.8-RC1 was just released. dependencyGraph and dependencyTree both do not work with it. Build fails with:

```
[error] (compile:ivyReport) java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
```

**Comment by eed3si9n** [comment]
This is caused by the fact that sbt 0.13.8 uses a new `ModuleSettings` called `InlineConfigurationWithExcludes`. You can test for the class name reflectively and grab the `module` field via structural subtyping to avoid adding dependency to sbt 0.13.8 code base. I can send a PR for this.

**Comment by jrudolph** [comment]
@eed3si9n A PR would be much appreciated as I currently don't have much time to look into it.

**Comment by pyetras** [comment]
+1

**Comment by malchmih** [comment]
+1

**Comment by jehrhardt** [comment]
:+1:

**Comment by vhiairrassary** [comment]
+1 to see the support for sbt 0.13.8

**Comment by AlaricCalmette** [comment]
:+1:

**Comment by nitay** [comment]
Is there going to be a release with the fix soon?

**Comment by nicolas** [comment]
+1

**Comment by probepark** [comment]
:+1:

**Comment by jrudolph** [comment]
I just released version 0.7.5 which should now support sbt 0.13.8 as well. Thanks again, @eed3si9n for the fix.

**Comment by hseeberger** [comment]
Thanks for the release. Works like a charm.

**Comment by briantopping** [comment]
Definitely, thanks guys!
