### ISSUE TITLE
How to save to file the result of dependency-tree

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [jrudolph/sbt-dependency-graph#71]
I have several hundreds dependencies, and I prefer to save it to a file, so that I can place bookmarks, search and so on.

I've tried ivyReport but provides an unreadable report.

Any suggestion?

**Comment by jrudolph** [comment]
Sorry for never answering your question, @DavidPerezIngeniero. Do you still need help with this?

**Comment by DavidPerezIngeniero** [comment]
It is not urgent, but I would be interested in any hint you can provide.

**Comment by jrudolph** [comment]
Next version will get support through the solution in #165.

**Comment by DavidPerezIngeniero** [comment]
Thanks!
