### ISSUE TITLE
How to install this plugin locally?

### ISSUE THREAD

**Issue by Sitin** [jrudolph/sbt-dependency-graph#75]
We want to add this plugin to repository but it seems it doesn't auto loads.

**Comment by sokrahta** [comment]
See the readme: https://github.com/jrudolph/sbt-dependency-graph/blob/master/README.md#how-to-use
It's not an autoplugin, so you must add `graphSettings` to the project build or global configuration.

**Comment by danbim** [comment]
I'm new to sbt and struggled to understand the readme, too. Maybe it would help to change

> apply the plugin's settings in ~/.sbt/0.13/global.sbt, the global build configuration:

into

> apply the plugin's settings in ~/.sbt/0.13/global.sbt, the global build configuration, by adding the following line:

To me it is not obvious that the line does "apply" anything...

**Comment by jrudolph** [comment]
@danbim yes, good point. I made the change. In the end, the real fix will come by making sbt-dependency-graph an auto-plugin as suggested in #51 which I will do when I finally find the time.
