### ISSUE TITLE
Following readme causes error 

### ISSUE THREAD

**Issue by leithaus** [jrudolph/sbt-dependency-graph#78]
Adding: net.virtualvoid.sbt.graph.Plugin.graphSettings

to ~/.sbt/0.13/global.sbt

causes all tasks to error:

bash-3.2$ sbt clean
/Users/lgm/.sbt/0.13/global.sbt:1: error: not found: value net
net.virtualvoid.sbt.graph.Plugin.graphSettings
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
bash-3.2$

**Comment by jrudolph** [comment]
This would mean, that for some reason the `addSbtPlugin` in `~/.sbt/0.13/plugins/plugins.sbt` wasn't effective. Can you post what you got in there?

**Comment by jrudolph** [comment]
Closing because of missing info. Please reopen if necessary.
