### ISSUE TITLE
Error during plugin dependency resolution

### ISSUE THREAD

**Issue by Kendos-Kenlen** [jrudolph/sbt-dependency-graph#79]
Hi,

I need to add JSON export to you plugin, but when I try to run scriped, I've the following error :

> \> scripted
Running sbt-dependency-graph / ignoreScalaLibrary
[info] Getting org.scala-sbt sbt 0.13.0 ...
[info] :: retrieving :: org.scala-sbt#boot-app
[info] 	confs: [default]
[info] 	43 artifacts copied, 0 already retrieved (12440kB/40ms)
[info] Getting Scala 2.10.2 (for sbt)...
[info] :: retrieving :: org.scala-sbt#boot-scala
[info] 	confs: [default]
[info] 	5 artifacts copied, 0 already retrieved (24390kB/19ms)
[info] [info] Loading project definition from /tmp/sbt_fd43f870/ignoreScalaLibrary/project
[info] [info] Updating {file:/tmp/sbt_fd43f870/ignoreScalaLibrary/project/}ignorescalalibrary-build...
[info] [info] Resolving net.virtual-void#sbt-dependency-graph;0.7.5-SNAPSHOT ...
[info] [warn] 	module not found: net.virtual-void#sbt-dependency-graph;0.7.5-SNAPSHOT
[info] [warn] ==== typesafe-ivy-releases: tried
[info] [warn]   http://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.10/sbt_0.13/0.7.5-SNAPSHOT/ivys/ivy.xml
[info] [warn] ==== sbt-plugin-releases: tried
[info] [warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.10/sbt_0.13/0.7.5-SNAPSHOT/ivys/ivy.xml
[info] [warn] ==== local: tried
[info] [warn]   /home/pogam-_g/.ivy2/local/net.virtual-void/sbt-dependency-graph/scala_2.10/sbt_0.13/0.7.5-SNAPSHOT/ivys/ivy.xml
[info] [warn] ==== public: tried
[info] [warn]   http://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.10_0.13/0.7.5-SNAPSHOT/sbt-dependency-graph-0.7.5-SNAPSHOT.pom
[info] [info] Resolving org.scala-lang#scala-library;2.10.2 ...
       [info] Resolving org.scala-sbt#sbt;0.13.0 ...
       [info] Resolving org.scala-sbt#main;0.13.0 ...
       [info] Resolving org.scala-sbt#actions;0.13.0 ...
       [info] Resolving org.scala-sbt#classpath;0.13.0 ...
       [info] Resolving org.scala-sbt#launcher-interface;0.13.0 ...
       [info] Resolving org.scala-sbt#interface;0.13.0 ...
       [info] Resolving org.scala-sbt#io;0.13.0 ...
       [info] Resolving org.scala-sbt#control;0.13.0 ...
       [info] Resolving org.scala-lang#scala-compiler;2.10.2 ...
       [info] Resolving org.scala-lang#scala-reflect;2.10.2 ...
       [info] Resolving org.scala-sbt#completion;0.13.0 ...
       [info] Resolving org.scala-sbt#collections;0.13.0 ...
       [info] Resolving jline#jline;2.11 ...
       [info] Resolving org.scala-sbt#api;0.13.0 ...
       [info] Resolving org.scala-sbt#compiler-integration;0.13.0 ...
       [info] Resolving org.scala-sbt#incremental-compiler;0.13.0 ...
       [info] Resolving org.scala-sbt#logging;0.13.0 ...
       [info] Resolving org.scala-sbt#process;0.13.0 ...
       [info] Resolving org.scala-sbt#relation;0.13.0 ...
       [info] Resolving org.scala-sbt#compile;0.13.0 ...
       [info] Resolving org.scala-sbt#persist;0.13.0 ...
       [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
       [info] Resolving org.scala-sbt#classfile;0.13.0 ...
       [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.0 ...
       [info] Resolving org.scala-sbt#ivy;0.13.0 ...
       [info] Resolving org.scala-sbt#cross;0.13.0 ...
       [info] Resolving org.apache.ivy#ivy;2.3.0-rc1 ...
       [info] Resolving com.jcraft#jsch;0.1.46 ...
       [info] Resolving org.scala-sbt#run;0.13.0 ...
       [info] Resolving org.scala-sbt#task-system;0.13.0 ...
       [info] Resolving org.scala-sbt#tasks;0.13.0 ...
       [info] Resolving org.scala-sbt#tracking;0.13.0 ...
       [info] Resolving org.scala-sbt#cache;0.13.0 ...
       [info] Resolving org.scala-sbt#testing;0.13.0 ...
       [info] Resolving org.scala-sbt#test-agent;0.13.0 ...
       [info] Resolving org.scala-sbt#test-interface;1.0 ...
       [info] Resolving org.scala-sbt#main-settings;0.13.0 ...
       [info] Resolving org.scala-sbt#apply-macro;0.13.0 ...
       [info] Resolving org.scala-sbt#command;0.13.0 ...
       [info] Resolving org.scala-sbt#compiler-interface;0.13.0 ...
       [info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.0 ...
       [info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.0 ...
       [info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.0 ...
       [info] Resolving org.scala-lang#jline;2.10.2 ...
       [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	:: net.virtual-void#sbt-dependency-graph;0.7.5-SNAPSHOT: not found
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 
[info] [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[info] [warn] 		net.virtual-void:sbt-dependency-graph:0.7.5-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[info] [warn] 
[info] sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.7.5-SNAPSHOT: not found
[info] 	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
[info] 	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
[info] 	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
[info] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
[info] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
[info] 	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
[info] 	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
[info] 	at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
[info] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
[info] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
[info] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
[info] 	at xsbt.boot.Using$.withResource(Using.scala:11)
[info] 	at xsbt.boot.Using$.apply(Using.scala:10)
[info] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
[info] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
[info] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[info] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[info] 	at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
[info] 	at sbt.IvySbt.withIvy(Ivy.scala:101)
[info] 	at sbt.IvySbt.withIvy(Ivy.scala:97)
[info] 	at sbt.IvySbt$Module.withModule(Ivy.scala:116)
[info] 	at sbt.IvyActions$.update(IvyActions.scala:121)
[info] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1144)
[info] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1142)
[info] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1165)
[info] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1163)
[info] 	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
[info] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1167)
[info] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1162)
[info] 	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
[info] 	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1170)
[info] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1135)
[info] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1113)
[info] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
[info] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info] 	at sbt.Execute.work(Execute.scala:244)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info] [error] (*:update) sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.7.5-SNAPSHOT: not found
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[error] x sbt-dependency-graph / ignoreScalaLibrary
[trace] Stack trace suppressed: run last *:scripted for the full output.
[error] (*:scripted) Remote sbt initialization failed
[error] Total time: 7 s, completed Aug 24, 2015 4:33:35 PM

How can I solve it ? I'm sorry, I'm a totally Scala/SBT beginner (It's the first time I use them).
Other question, how can I run the plugin to test it on my computer ?

Thank you for your answer.

**Comment by jrudolph** [comment]
Hi @Kendos-Kenlen, try running `publish-local` in sbt first which will publish the artifact to your local ivy repository with the configured version which currently is `0.7.5-SNAPSHOT`. You can then just follow the instructions about how to use the plugin replacing the released version with the snapshot version.

`scripted` also expects the current version to be available locally so running `publish-local` first should make it work.

**Comment by Kendos-Kenlen** [comment]
Everything works, thank you ! :)

**Comment by jrudolph** [comment]
Nice :)

**Comment by Kendos-Kenlen** [comment]
HI,

Just, I've a new question : is the plugin available for SBT 0.11 ?

**Comment by jrudolph** [comment]
@Kendos-Kenlen in which way was it unsuccessful?

**Comment by jrudolph** [comment]
And yes it should work :)

**Comment by Kendos-Kenlen** [comment]
I'm trying to crawl the dependencies from this project :

But I've a dependency resolution error with SBT 0.11 :https://github.com/chrislewis/hazelbox

>[info] Loading global plugins from /home/pogam-_g/.sbt/plugins
[info] Updating {file:/home/pogam-_g/.sbt/plugins/}default-607b65...
[warn]  module not found: net.virtual-void#sbt-dependency-graph;0.7.5
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.9.1/sbt_0.11.0/0.7.5/ivys/ivy.xml
[warn]   -- artifact net.virtual-void#sbt-dependency-graph;0.7.5!sbt-dependency-graph.jar:
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.9.1/sbt_0.11.0/0.7.5/jars/sbt-dependency-graph.jar
[warn] ==== local: tried
[warn]   /home/pogam-_g/.ivy2/local/net.virtual-void/sbt-dependency-graph/scala_2.9.1/sbt_0.11.0/0.7.5/ivys/ivy.xml
[warn]   -- artifact net.virtual-void#sbt-dependency-graph;0.7.5!sbt-dependency-graph.jar:
[warn]   /home/pogam-_g/.ivy2/local/net.virtual-void/sbt-dependency-graph/scala_2.9.1/sbt_0.11.0/0.7.5/jars/sbt-dependency-graph.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.9.1_0.11.0/0.7.5/sbt-dependency-graph-0.7.5.pom
[warn]   -- artifact net.virtual-void#sbt-dependency-graph;0.7.5!sbt-dependency-graph.jar:
[warn]   http://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.9.1_0.11.0/0.7.5/sbt-dependency-graph-0.7.5.jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/net/virtual-void/sbt-dependency-graph_2.9.1_0.11.0/0.7.5/sbt-dependency-graph-0.7.5.pom
[warn]   -- artifact net.virtual-void#sbt-dependency-graph;0.7.5!sbt-dependency-graph.jar:
[warn]   http://scala-tools.org/repo-releases/net/virtual-void/sbt-dependency-graph_2.9.1_0.11.0/0.7.5/sbt-dependency-graph-0.7.5.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: net.virtual-void#sbt-dependency-graph;0.7.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          net.virtual-void:sbt-dependency-graph:0.7.5 (sbtVersion=0.11.0, scalaVersion=2.9.1)
[warn] 
[error] {file:/home/pogam-_g/.sbt/plugins/}default-607b65/*:update: sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.7.5: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

No problem with SBT 13.
Maybe I don't require the plugin with the good way. I followed the README but instead of creating plugin in ~/.sbt/0.13, I created them in ~/.sbt (SBT 0.11 look to not care about ~/.sbt/0.11).

**Comment by jrudolph** [comment]
If you look here, it seems that only sbt `0.11.0` specifically is not supported. Would it be possible to update to sbt 0.11.3?

**Comment by Kendos-Kenlen** [comment]
Owh I see ... Maybe it could be a good idea to specify it in the readme.
Thank you !
