### ISSUE TITLE
Use sbt update task to build dependency graph

### ISSUE THREAD

**Issue by muuki88** [jrudolph/sbt-dependency-graph#82]
SBT builds a classpath with the `update` task [1](https://github.com/sbt/sbt/blob/0.13.9/main/src/main/scala/sbt/Defaults.scala#L1006), [2](https://github.com/sbt/sbt/blob/0.13.9/main/src/main/scala/sbt/Defaults.scala#L1687-L1691). 

The values returned by the report can differ from the ones in the `cache-resolution` ivyReport. 

We ran into an issue during a finagle-upgrade. `org.apache.zookeeper:zookeeper:3.4.6` and `org.apache.zookeeper:zookeeper:3.5.0-alpha` both depend on `org.slf4j:slf4j-log4j12`, which is stated in the `UpdateReport` but not in the ivy-resolution, thus not in the dependency-graph.

**Comment by jrudolph** [comment]
Thanks, @muuki88 for the report. Do you have a reproduction?

AFAIU `update` uses some form of the ivy report (though not the XML one we use but the ivy's in-memory structures) to generate the classpath. So, I don't really understand why those reports would differ.

That said, you are definitely right that the ultimate goal should be to use the same data source for the report as sbt uses to build the classpath. Unfortunately, that's currently not the way `sbt-dependency-graph` is built so if we could find out what the underlying reason for the discrepancy we may find a smaller fix in the short-term.

**Comment by muuki88** [comment]
I will try to create a small project reproducing this issue :)

**Comment by muuki88** [comment]
I wasn't able to reproduce this in a single `build.sbt`. Maybe our levels of indirection lead to this issue. We have

`our-commons-library` (depending on finalge) -> `our-service-api` . If I put all the dependencies in a single `build.sbt` the excludes work correctly in both `sbt-dependency-graph` and sbt's `update`. You can close this. If necessary I'll reopen it if I find any clue why this happens.

**Comment by jrudolph** [comment]
Ok, thanks for verifying :)

**Comment by jkleckner** [comment]
@muuki88 Be open to the possibility of non-determinism as described in #39 since your problem occurs when there is more than one build.sbt
