### ISSUE TITLE
List of dependencies.

### ISSUE THREAD

**Issue by alexeyr** [jrudolph/sbt-dependency-graph#85]
Sometimes, I'd like to see the deduplicated list of all dependencies instead of a tree. Is there a way to do this? If not, could you add a `dependencyList` command?

**Comment by dwijnand** [comment]
This should really be a plugin or a part of sbt-dependency-graph, but for any immediate needs: https://gist.github.com/dwijnand/06884f7dc5b43fe9b3b7

**Comment by dwijnand** [comment]
Cool!
